### ISSUE TITLE
Disclosure View Component

### ISSUE THREAD

**Issue by marianayovcheva** [citizensadvice/design-system#1718]
# Disclosure
The disclosure component already exists as part of the public-website and is used to show/hide search filters. It will also be used in the template letters. 

The time has come to extract a generic component that allows us to:
- provide button titles:
   - required closed title
   - optional open title (if not provided, the closed title will be used)
- provide content that will appear when the disclosure is open
___
- does your component need to be used by other products or services?
> it is currently used by the [search filters](https://www.citizensadvice.org.uk/s/?q=benefits) on the public-website and by [template letters](https://web.develop.content.citizensadvice.org.uk/new-platform/a-template-letter/)
- does something similar already exist in the design system
> No, but it can reuse the show-hide functionality with additional js (similar to on this page component)
- is there a product team that would perform the research, design, development and QA work associate with building this component?
> Probably content-platform?
- do you have any user stories / scenarios that describe the component?
> not currently

### Code

- provide a link to your component working in a dev or prod environment
> https://www.citizensadvice.org.uk/s/?q=benefits&filter_by=advice
- provide links to the code for this component
> https://github.com/citizensadvice/public-website/blob/develop/app/components/disclosure_component.rb
> https://github.com/citizensadvice/public-website/blob/develop/app/components/disclosure_component.html.haml

### Usability

- have you tested the component with the intended user group? Please include any links to research documentation in your proposal
> It was initially tested on equivalent for search filters on the Intranet. It was not used in the end, however, once prompted the users were able to use the toggle so the behaviour test passed.

### Accessibility

- have you ensured your component meets WCAG 2.X AA guidelines? Include test protocols from external audits or notes from internal tests
- have you tested your component with a screen reader?
- have you tested your component by using only the keyboard to interact with it?
> not yet tested

### Quality

- provide links to any appropriate automated tests you have written
  - unit tests
  > https://github.com/citizensadvice/public-website/blob/develop/spec/components/disclosure_component_spec.rb
  - behavioural tests
  > can be extracted from here: https://github.com/citizensadvice/public-website/blob/develop/features/advice/public/advice_only_search.feature#L5
  - visual regression tests
  > this test can be modified to be more general and not search specific: https://github.com/citizensadvice/public-website/blob/develop/testing/visual-regression/scenarios/public-advice.js#L76

**Comment by marianayovcheva** [comment]
@davidsauntson, here are the bits I'm not sure about:
- _does your component need to be used by other products or services?_ - not sure if advisernet or intranet will use it?
- _do you have any user stories / scenarios that describe the component?_ - I couldn't find anuthing specific in the features folder but wanted to doublecheck
- _Usability_ - this one I've just copy pasted from the other component, but will be useful to know if there is a specific place I can check
- _Accessibility_  - the other components I've been working on had reference to [this accessibility review](https://citizensadvice.atlassian.net/wiki/spaces/NP/pages/2526347313/Accessibility+reviews+-+external), but looking at the search page there, it looks like the component was added after the review so I'm not sure if there are other tests it was covered by

**Comment by davidsauntson** [comment]
Thanks for this! My thoughts:

> @davidsauntson, here are the bits I'm not sure about:
> 
> * _does your component need to be used by other products or services?_ - not sure if advisernet or intranet will use it?
I don't think either use it at the moment, but it is now in template letters (https://web.develop.content.citizensadvice.org.uk/new-platform/a-template-letter/)

> * _do you have any user stories / scenarios that describe the component?_ - I couldn't find anuthing specific in the features folder but wanted to doublecheck
No, not yet

> * _Usability_ - this one I've just copy pasted from the other component, but will be useful to know if there is a specific place I can check
I know @davidrapson saw some testing when the digital workplace team used in in their search page, but the context was pretty different so not how how applicable it would be

> * _Accessibility_  - the other components I've been working on had reference to [this accessibility review](https://citizensadvice.atlassian.net/wiki/spaces/NP/pages/2526347313/Accessibility+reviews+-+external), but looking at the search page there, it looks like the component was added after the review so I'm not sure if there are other tests it was covered by
💯  correct- it was added after the accessibility audits were done

There are some behavioural tests that cover it in the tests in `advice_only_search.feature` in public website - we'd want to extract these and plop them into the design system probably.

**Comment by davidrapson** [comment]
> I know @davidrapson saw some testing when the digital workplace team used in in their search page, but the context was pretty different so not how how applicable it would be

Yeah we initially tested using it on equivalent for search filters on the Intranet and in a different context. Our finding there was that it made more sense to show the filters inline so we don't use the disclosure component. Once prompted folks were able to use the toggle fine though so the behaviour was OK, just not a necessary design pattern for our context.

**Comment by marianayovcheva** [comment]
Great, thank you both! I've now updated the issue with the comments/suggestions

**Comment by mrdaniellewis** [comment]
Currently Casebook has a very weird disclosure design, which I do not like.

While Casebook doesn't use the design system, I would love there to be a consistent disclosure design across all products and I'd really like to get rid of the current Casebook design.

----

<img width="472" alt="Screenshot 2022-01-07 at 10 05 40" src="https://user-images.githubusercontent.com/554788/148528192-54c20348-c67e-4e76-b14f-90715e56a232.png">

This is not a good design.  The entire "Benefits Collapse" is actually the button, but only the "Collapse" has been styled as a button.  The result is, a screen reader will read out "Benefits Collapse Expanded"

Also we've been told our arrow is upside down (see the verb / adjective thing below) and confusing on a high zoom.

----

I have a couple of questions.

1. These days, could you just use `<details>` / `<summary>`? - what about IE11 - they will just always see them fully expanded, which seems a reasonable compromise. 
2. It is possible search engines, or even the browser search tool, will handle indexing of `<details>` / `<summary>` better, but I don't have any evidence of this.
3. Do you want to combine a disclosure with a heading.  The heading needs to go on the outside of the button so you can't use `<details>` / `<summary>`.  There are some [disclosures on the classic Episerver](https://www.citizensadvice.org.uk/benefits/universal-credit/before-you-apply/what-universal-credit-is/#h-applying-for-new-style-jsa) that use headings.  The JS for these will open the disclosure if the url hash points to them.  Does that need to be considered?  I think it even works for nested disclosures.
4. The disclosure button is styled as a link.  I thought that was bad as it creates a confusing experience in Dragon where you have to specify if you want to click a button or a link.   [ARIA practices](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-faq.html) has not styled them as a link, but I'm not sure it is clear they are clickable.
5. Is the `+` / `-` set in stone.  [gov.uk is now using an arrow](https://design-system.service.gov.uk/components/details/), which is more consistent with the native styling.  I think the question comes down to, should the button show the current state of the disclosure (an adjective eg "collapsed"), or what the button will do (a verb eg "expand").  Casebook is using verbs, and this design is using verbs in the form of symbols (`+` / `-`) or in the template letters (`+ View` / `- Hide`).  However native uses adjectives (`▶` / `▼`), and so does aria (`aria-expanded`).  The tree widgets, eg file manager, on most operating systems also opt for arrows (`▶` / `▼`).
6. In the template letter example the label changes when it is expanded or contracted (`+ Show template letter` / `- Hide template letter`).  On Casebook, most disclosures are just a static heading (with the weird "Expand" / "Collapse" button thing), but we have a few disclosures that do this as well eg `Show past addresses` / `Hide past addresses`.  Possible on Casebook we could get away with just a `▶ Past addresses` button, but on the public website I can see a floating `▶ Template letter` button would be a little confusing.  Are there two use cases here?  eg, one is a more standard `<details>` / `<summary>` without a dynamic label, and the other is call to action button.

[gov.uk also has an accordion](https://design-system.service.gov.uk/components/accordion/).  To me an accordion is just a set of disclosures arranged vertically.  The odd thing is they've gone for the verb approach (▲/▼) on that design.  I don't like it.

**Comment by anneliwesterberg** [comment]
From what I remember Minnie saying, this filter pattern was chosen for public site search because it makes the filters less prominent. The majority of users won't change the filter from advice content so it didn't make sense to give the filters too much space. I'm assuming this might have been the reason you chose a different approach for the intranet @davidrapson?

I think there's a case for adding this to the design system, but we need to make it clear that this pattern has a specific use case; to hide functionality that most users won't need. It should not be used just to declutter an interface. If you have functionality that a lot of users will need, the options should not be hidden as a lot of users will miss it. (For example the 'This advice applies to' switcher at the top of advice pages now lists all nations as most users missed the drop-down that was there before.)

**Comment by marianayovcheva** [comment]
@mrdaniellewis sorry for the delay in getting back to you! thanks for your comment - some very useful points!

- on points 1 - 3 about `<details>`/`<summary>` - good shout, I think it's something we can use here. I'll have a further read myself but I can also bring it up with AbilityNet.
The example from the epi server would be using the existing Targeted content component: https://citizensadvice.github.io/design-system/?path=/story/components-targeted-content--default
- 4 - 5, I will check those with the designers to get their thoughts on this and see if there are potential design changes. I think that Kostas and James don't have github so I'll move the discussion to slack.
- 6 - I think the button text will be dependant on how the people use the component - i.e it will be easy to define it

From the screenshot of the casebook it looks like it can potentially be closer to the existing targeted content component: https://citizensadvice.github.io/design-system/?path=/story/components-targeted-content--default  (which now that I think about it is quite similar to the disclosure functionality)

Either way, I think the disclosure can be a candidate for our experimental feature and we can share with the team before making it live

**Comment by anneliwesterberg** [comment]
@mrdaniellewis You are right about point 4 - it should ideally not use the link styling as it's not a link.

As for point 5 - I definitely see merit in moving to native (and aria) behaviour for accessibility purposes - however that would impact our targeted content component as well so that would have to be reviewed as part of this work. @JamesR-CA What are your views on this?

**Comment by davidrapson** [comment]
`details` / `summary` fails on a few accessibility points. We _deliberately_ moved away from it for targeted content as details/summary sadly clobbers the semantics of any elements inside it. For example headings would no longer get treated as headings.

I'll see if I can dig out some more context, and I think there's a GDS design system thread about the same thing floating around.

**Comment by JamesR-CA** [comment]
On point 4 - the Details GDS page, research section does show that from their research it isn't necessarily a good option. 

> Research on this component
> There is evidence that some users avoid clicking the link to show more details, as they think it will take them away from the page.
> 
> There are concerns that some users of voice assist software will not be able to interact with the component. Some software might require the user to specifically refer to the link to show more details as a button in order to interact with it.
> 
> When printing, there is currently no way to force the page to show details hidden inside a details component. This issue has been raised with the W3C.

@anneliwesterberg - worth speaking with the content team on how they are using/plan to use Targeted Content. But yes - it seems that we would need to unpack how these (targeted content and details) would be used and to see how they would provide a intuitive experience for users coming across these components.

**Comment by JamesR-CA** [comment]
@mrdaniellewis - what are you thoughts on the W3C aria practice examples for accordions - which use the up and down arrows. https://w3c.github.io/aria-practices/examples/accordion/accordion.html

**Comment by davidsauntson** [comment]
@davidrapson  is right about the conscious decision to move away from `details/summary` for targeted content.  But the use case for that feels very different to me, so I don't have a problem with it having a different implementation.  

The way we have used the proposed disclosure so far would not require the text on the `summary` element to have any semantic meaning (like being a header), so I think it's probably ok to use `details/summary`.  The current implementation also just accepts a `string` for the details part - you couldn't actually construct one with anything else at the moment.  Is there mileage in:
- using `details/summary`
- continuing to restrict what can be set as the `details` text to a `string`
- making the accessibility points explicit in the docs

**Comment by Kostas-citizens** [comment]
I have contacted Joana from Ability Net, she came back with the following advice: 

From an accessibility point of view, there is not a requirement in terms of the symbol used, as long as the symbol is used consistently throughout the site. This relates to Success Criterion [3.2.4: Consistent Identification](https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification.html). Although this Success Criteria is more directed to the label/accessible name provided being consistent, the symbol used for disclosure components communicates the expandable state and, therefore, should be used consistently.

I would say that the chevron icon, in your Casebook example, is the most commonly used symbol to communicate an expandable section. This is commonly used not only for single disclosures, but also for accordions. An example can be found here: [WAI-ARIA Practices – Accordion example](https://www.w3.org/TR/wai-aria-practices-1.2/examples/accordion/accordion.html).

Examples like the one that you shared (ARIA) are commonly used on FAQ pages. In terms of the symbol, the purpose is the same but instead of the down/up chevron approach, it uses chevrons pointing right/down. However, in terms of the position of the symbol, it is usually adapted to what is most convenient. For example, for small buttons the symbol is usually placed to the right of the text but for lengthy links this can be a bit challenging.

Let’s say that it is an FAQ page, where all disclosure titles have different lengths. For design consistency, the symbol is commonly aligned for all FAQs, and this may cause issues if the symbol is aligned on the right. For example, if the symbol is placed too far from the text some users may not be able to understand the visual association between them. The solution for these cases is having all chevrons aligned to the left.

Regarding the “+/-” symbols as a disclosure state indicator, although it is not as common as the chevron, it can also be used. In that case, the example on the template letter page seems to be a bit clearer, as it does not rely on the symbol alone to communicate this. Therefore, if a user is not familiar with the symbol, the text “view/hide” adds this information to the element.

In terms of the text underline, although the underline is commonly used and recommended for links, there are no requirements in terms of styling. In this case, the underline is what represents best that the element is interactive, especially for users who are not familiar with the symbols, as the button does not contain an outline.

**Comment by marianayovcheva** [comment]
To summarise the discussion points and suggested approach:

- The design of the component will keep the current styles based on the discussion with AbilityNet
- For now the component will still use `<button>` the reasons for moving away from `<details>/<summary>` are:
  - accessibility concerns - as outlined in GDS docs for details - voice assist software, printing
  - browser support - it is not being fully supported in IE11 (though it will still display the component's open state)
  - we will still need JS to change the text on click

Please let me know if there are any concerns, ideas or questions.
